language: java
os: linux
jdk:
  - openjdk8
sudo: required
services:
  - docker
script:
  - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.7.1/jfrog-cli-linux-amd64/jfrog
  - chmod +x jfrog
  - mvn clean install
  - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD
  - ./jfrog rt u "target/*.jar" Travis-ci-maven --build-name=hello --build-number=$TRAVIS_BUILD_NUMBER --flat=false
  - ./jfrog rt bce hello $TRAVIS_BUILD_NUMBER
  - ./jfrog rt bp hello $TRAVIS_BUILD_NUMBER
  
