language: java
os: linux
jdk:
  - openjdk8
sudo: required
services:
  - docker
before_script:
  - sudo apt-get install wget
  # Install JFrog CLI
  - curl -fL https://getcli.jfrog.io | sh
  - sudo apt-get install docker
script:
  - mvn clean install
  - docker build -t test .
after_success:
  - docker login -u 8008598725 -p Dnsu@123
  - docker tag test dharma/test:36
  - docker push dharma/test:36
  - docker tag test dharma/test:latest
  - docker push dharma/test:latest
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop

