language: java
os: linux
jdk:
  - openjdk8
sudo: required
services:
  - docker
before_script:
  - sudo apt-get install wget
  # Install JFrog CLI
  - curl -fL https://getcli.jfrog.io | sh
  - sudo apt-get install docker
script:
  - mvn clean install
  - docker build -t test .
after_success:
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag test $DOCKER_USER/test-repo:$TRAVIS_BUILD_ID
  - docker push $DOCKER_USER/test-repo:$TRAVIS_BUILD_ID
  - docker tag test $DOCKER_USER/test-repo:latest
  - docker push $DOCKER_USER/test-repo:latest
#branches:
#  only:
#  - master
