language: java
jdk:
  - openjdk8
#script: mvn clean package
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop

jobs:
  include:
    - state: mvn clean
    - stage: mvn compile
    - stage: mvn test
    - stage: mvn package
    - stage: mvn install
