language: java
jdk:
  - openjdk8
script: mvn clean package
services:
  - docker
before_script:
  - docker install
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop
#notifications:
#  slack: okta-4xs8596:rHzaR8VWVpBBGkEcUI3YOwE7

