language: java
jdk:
  - openjdk8
#script: mvn clean package
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop

jobs:
  include:
    - stage: mvn clean package
      script: echo package
