language: java
jdk:
  - openjdk8
script: mvn clean package
sudo: required
services:
  - docker
before_script:
  - sudo yum install wget
  - sudo yum install docker
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop
#notifications:
#  slack: okta-4xs8596:rHzaR8VWVpBBGkEcUI3YOwE7

