language: java
os: linux
jdk:
  - openjdk8
sudo: required
services:
  - docker
before_script:
  - sudo apt-get install wget
  # Install JFrog CLI
  - curl -fL https://getcli.jfrog.io | sh
  - sudo apt-get install docker
script:
  - mvn clean install
  - docker build -t test .
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop

