language: java
os: linux
jdk:
  - openjdk8
sudo: required
services:
  - docker
before_script:
  - sudo apt-get install wget
  - sudo apt-get install docker
script:
  - mvn clean package
  - docker build -t test .
#branches:
#  only:
#  - master
  
#branches:
#  except:
#  - devlop
#notifications:
#  slack: okta-4xs8596:rHzaR8VWVpBBGkEcUI3YOwE7

