language: java
os: linux
jdk:
  - openjdk8
sudo: required
services:
  - docker
before_script:
  - sudo apt-get install wget
  # Install JFrog CLI
  - curl -fL https://getcli.jfrog.io | sh
  - sudo apt-get install docker
script:
  - mvn clean install
  - docker build -t test .
after_success:
  - docker images
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag test $DOCKER_USER/test-repo:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/test-repo:$TRAVIS_BUILD_NUMBER
  - docker tag test $DOCKER_USER/test-repo:latest
  - docker push $DOCKER_USER/test-repo:latest
  - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
  - ./jfrog rt u https://dharma.jfrog.io/artifactory/Travis-ci-maven/ Travis-ci-maven --build-name= DNagineni/hello --build-number=49
  - ./jfrog rt bce DNagineni/hello 49
  - ./jfrog rt bp DNagineni/hello 49
  
